#!/bin/bash

gen_header() {
    cat>${1}/${2}.h<<EOF
#pragma once

namespace Chili {

class $2 {
public:
};

} // namespace Chili

EOF
}

gen_source() {
    cat>${1}/${2}.cc<<EOF
#include "${2}.h"

namespace Chili {

// TODO

} // namespace Chili

EOF
}

gen_both() {
    gen_header include $1
    gen_source src $1
}

gen_test() {
    class=$1
    var=$(echo $class | sed 's/[a-z]//g' | tr '[:upper:]' '[:lower:]')
    cat>test/${class}Test.cc<<EOF
#include <gmock/gmock.h>

#include "${class}.h"

using namespace ::testing;

namespace Chili {

class ${class}Test : public Test {
public:
    ${class}Test() {
    }

protected:
};

TEST_F(${class}Test, constructs) {
    $class $var;
}

} // namespace Chili

EOF
}

gen_all() {
    gen_both $1
    gen_test $1
}

T=$1
shift

gen_$T "$@"
